baseURL = 'https://damiaodoesdev.blog/'
languageCode = 'pt-pt'
title = 'DamiaoDoesDev'
theme = 'minimal-blog'

[params]
description = "Um blog minimalista sobre desenvolvimento web e tecnologia"
author = "Damião"

[menu]
  [[menu.main]]
    name = "Início"
    url = "/"
    weight = 1
  
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  
  [[menu.main]]
    name = "Sobre"
    url = "/about/"
    weight = 3
